backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Feature Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "date" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: Author, name: author, widget: hidden, default: Adam Pagels }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
